[tool.poetry]
name = "pytest-golden"
version = "0.2.2"
description = "Plugin for pytest that offloads expected outputs to data files"
authors = ["Oleh Prypin <oleh@pryp.in>"]
license = "MIT"
repository = "https://github.com/oprypin/pytest-golden"
keywords = ["pytest", "pytest-plugin"]
classifiers = ["Framework :: Pytest"]
readme = "README.md"

[tool.poetry.plugins."pytest11"]
pytest-golden = "pytest_golden.plugin"

[tool.poetry.dependencies]
python = "^3.6"
pytest = ">=6.1.2"
"ruamel.yaml" = ">=0.16.12, <1.0"
atomicwrites = "^1.4.0"
dataclasses = {version = ">=0.7, <1.0", python = "<3.7"}
testfixtures = "^6.15.0"

[tool.poetry.dev-dependencies]
black = ">=20.8b1"
isort = "^5.6.4"
autoflake = "^1.4"
pytype = {version = ">=2021.04.15", markers = "python_version>='3.6' and python_version<'3.10' and sys_platform!='win32'"}  # Skip on Windows

[tool.black]
line-length = 100

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pytest.ini_options]
addopts = "--tb=native"
enable_assertion_pass_hook = true
norecursedirs = "example"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
